# Generated by Django 3.1.2 on 2020-10-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201020_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
